version: 0.2

env:
  variables:
    fileUsEast2: "parameters-us-east-2.json"  
    VERSION_TAG: "12ART56"
  exported-variables:   
    - fileUsEast2  # Build variables for BuildVariables NameSpace
    - VERSION_TAG
    

phases:
  install:
    runtime-versions:
      python: 3.11 
    
  build:
    commands:
      - aws cloudformation validate-template --template-body file://ec2-instance.yml
      
      - echo $role #Pipeline variables passed to build stage

      - echo $account_id #Pipeline variables passed to build stage

      - echo $fileUsEast2
      
      - echo $COMMIT_ID
     
      - jq '.Parameters.InstanceType = "t2.medium"' parameters-ca.json
      
      - echo "Hello"
      

artifacts:
  files:
    - ec2-instance.yml
    - parameters-ca.json
    - parameters-us-east-2.json