AWSTemplateFormatVersion: 2010-09-09

Description: AWS CloudFormation Sample Template EC2ChooseAMI

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.

  InstanceName:
    Description: EC2 instance name 
    Type: String
    Default: Quick-Server
  
  InstanceProfile:
    Description: EC2 instance name 
    Type: String
    Default: CodeDeployDemo-EC2-Instance-Profile

  VolumeSize:
    Description: EC2 instance name 
    Type: Number
    Default: 16

  SG:
    Description: Security Group
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0cc05d246dbc6682c
  
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  Subnet:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: AWS::EC2::Subnet::Id
    Default: subnet-05c24e818412fadb4
  
  # KeyName:
  #   Description: Name of an existing EC2 KeyPair to enable SSH access to the web server
  #   Type: AWS::EC2::KeyPair::KeyName
  #   ConstraintDescription: can only be an existing key pair

Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref InstanceProfile
      SourceDestCheck: true
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref VolumeSize
      # KeyName: !Ref KeyName
      SubnetId: !Ref Subnet
      SecurityGroupIds:
        - !Ref SG
      Tags:
        - Key: Name
          Value: !Ref InstanceName
        - Key: Report
          Value: PVRE
        - Key: auto-delete
          Value: 'no'
      UserData: 
        "Fn::Base64":
          !Sub |
            #!/bin/bash            
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo yum install unzip -y
            sudo yum install nano -y
            unzip awscliv2.zip
            sudo ./aws/install
            sudo amazon-linux-extras install docker
            sudo yum install docker -y
            sudo service docker start
            sudo usermod -a -G docker ec2-user
            sudo yum update -y
            sudo amazon-linux-extras install nginx1
            sudo yum install nginx -y
            export USERNAME={username}
            export PASSWORD={DBP  }
            

Outputs:
  PublicIp:
    Value: !GetAtt Ec2Instance.PublicIp
    Description: Server's PublicIp Address